INSERT INTO category (department_name) VALUES ('American');
INSERT INTO category (department_name) VALUES ('Italian');
INSERT INTO category (department_name) VALUES ('Mexican');
INSERT INTO category (department_name) VALUES ('Fast Food');
INSERT INTO unit_of_measure (units) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (units) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (units) VALUES ('Cup');
INSERT INTO unit_of_measure (units) VALUES ('Pinch');
INSERT INTO unit_of_measure (units) VALUES ('Ounce');
INSERT INTO unit_of_measure (units) VALUES ('Dash');
INSERT INTO unit_of_measure (units) VALUES ('Not Applicable');